vim.opt.termguicolors = true -- true colors
vim.opt.cursorline = true -- highlight current line
vim.opt.nu = true -- line numbers
vim.opt.relativenumber = true -- relative line numbers
vim.opt.whichwrap = '<,>,[,]' -- go up/down at end of line
-- vim.opt.clipboard = 'unnamedplus' -- use system clipboard
vim.opt.clipboard = 'unnamed' -- use vim clipboard
vim.opt.expandtab = false -- use spaces instead of tabs
vim.opt.shiftwidth = 2 -- spaces used for each indentation
vim.opt.tabstop = 2 -- how many spaces a tab represents
vim.opt.wrap = false -- wrap line if it doesn't fit on screen
-- vim.opt.linebreak = true -- when wrapping wont't split words
vim.opt.undofile = true -- persistent undo
vim.opt.undodir = os.getenv("HOME") .. "/.cache/nvim/undodir"
vim.opt.confirm = true -- ask for confirmation when closing with unsaved changes
-- vim.opt.swapfile = false -- disable swap file when closing without saving
-- vim.opt.colorcolumn = '80,100' -- highlight column
vim.opt.ignorecase = true -- case insensitive search
vim.opt.smartcase = true -- search vim you get vim Vim VIM vIm
vim.opt.autocomplete = true -- automatically show completion menu
vim.opt.completeopt = 'menu,popup,fuzzy,menuone'
